// 生成静态文章派生数据（2A 阶段：正文出主包）
// 输出：
//   1) public/search-index.json   — 全文搜索索引（slug/title/tags/body 纯文本），运行时 fetch 后建 Fuse
//   2) src/data/generated-meta.ts — POST_SUMMARY / POST_MINUTES 元数据，替代运行时对 md 正文的同步依赖
// 由 articles.ts + src/content/*.md 驱动，prebuild 阶段在 gen:site 前自动执行。
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const src = fs.readFileSync(path.join(root, 'src/data/articles.ts'), 'utf8')
const re = /\{\s*title:\s*"([^"]*)",\s*date:\s*"([^"]*)",\s*tags:\s*\[([^\]]*)\],\s*(?:kind:\s*"[^"]*",\s*)?path:\s*"([^"]*)",\s*slug:\s*"([^"]*)"/g

const posts = []
let m
while ((m = re.exec(src))) {
  const [, title, date, tagsRaw, mdPath, slug] = m
  const tags = [...tagsRaw.matchAll(/"([^"]*)"/g)].map(x => x[1])
  posts.push({ title, date, tags, path: mdPath, slug })
}

function stripFrontMatter(md) {
  if (md.startsWith('---')) {
    const end = md.indexOf('---', 3)
    if (end !== -1) return md.substring(end + 3).trim()
  }
  return md
}

/** 剥离原始 HTML（标签、注释、script/style 整块），避免标签及其属性污染纯文本 */
function stripHtml(html) {
  return html
    .replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]*>/g, ' ')
}

/** 正文去符号纯文本（用于摘要 / 阅读时长 / 搜索索引，与 src/lib/blog.ts 语义一致） */
function toPlainText(md) {
  return stripHtml(stripFrontMatter(md))
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    // eslint-disable-next-line no-useless-escape -- 字符类内含字面 [ ，保留转义写法避免歧义
    .replace(/[#*`>_~\-\[\]()!|]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function getSummary(md) {
  const text = toPlainText(md)
  return text.length > 100 ? text.substring(0, 100) + '...' : text
}

function estimateReadingTime(md) {
  const text = toPlainText(md)
  const chineseChars = (text.match(/[\u4e00-\u9fff]/g) || []).length
  const englishWords = text.replace(/[\u4e00-\u9fff]/g, '').split(/\s+/).filter(Boolean).length
  return Math.max(1, Math.ceil(chineseChars / 300 + englishWords / 200))
}

const summaries = {}
const minutes = {}
const index = []
for (const p of posts) {
  const raw = fs.readFileSync(path.join(root, 'src/content', p.path), 'utf8')
  summaries[p.slug] = getSummary(raw)
  minutes[p.slug] = estimateReadingTime(raw)
  index.push({ slug: p.slug, title: p.title, tags: p.tags || [], body: toPlainText(raw) })
}

// search-index.json（public/ 会被 Vite 原样拷贝到 dist）
fs.writeFileSync(
  path.join(root, 'public/search-index.json'),
  JSON.stringify(index) + '\n'
)

// generated-meta.ts
const tsBody = [
  '// AUTO-GENERATED by scripts/gen-posts.mjs — 勿手改；prebuild 自动运行重新生成',
  '// 派生自 src/data/articles.ts + src/content/*.md',
  'export const POST_SUMMARY: Record<string, string> = ' + JSON.stringify(summaries, null, 2),
  '',
  'export const POST_MINUTES: Record<string, number> = ' + JSON.stringify(minutes, null, 2),
  '',
].join('\n')
fs.writeFileSync(path.join(root, 'src/data/generated-meta.ts'), tsBody)

console.log(`[gen-posts] ${posts.length} 篇 -> search-index.json ${(index.length)} 条 / generated-meta.ts 已生成`)
