// AUTO-GENERATED by scripts/gen-posts.mjs — 勿手改；prebuild 自动运行重新生成
// 派生自 src/data/articles.ts + src/content/*.md
export const POST_SUMMARY: Record<string, string> = {}

export const POST_MINUTES: Record<string, number> = {}
